openapi: 3.0.0
info:
  title: "todo-sample"
  version: 1.0.0
paths:
  /todos/{todoid}:
    get:
      summary: "todo情報API"
      responses:
        200:
          description: "成功時のレスポンス"
          content:
            application/json: # レスポンスの形式指定
              schema:
                type: object
                properties:
                  id:
                    type: "integer"
                    format: "int64"
                    example: 1
                  title:
                    type: "string"
                    example: "国民年金申請"
                  memo:
                    type: "string"
                    example: "年金手帳を持っていく"
                  implementationDate:
                    type: "string"
                    format: "date"
                    example: "2021-06-17"
                  dueDate:
                    type: "string"
                    format: "date"
                    example: "2021-06-17"
                  priorityColor:
                    type: "string"
                    example: "#ff0000"
                  completeFlag:
                    type: "boolean"
                    example: true